#!/bin/sh
HOST=$1

if [ $# -eq 2 ]; then
  PORT=$2;
else
  PORT=5672;
fi

echo " --- Configuring to $HOST:$PORT"

qpid-config -a $HOST:$PORT add exchange direct core.direct --durable
qpid-config -a $HOST:$PORT add exchange topic core.topic --durable
qpid-config -a $HOST:$PORT add queue core.client-core --durable
qpid-config -a $HOST:$PORT add queue core.service-core --durable
qpid-config -a $HOST:$PORT add queue core.trace --durable
qpid-config -a $HOST:$PORT bind core.direct core.client-core core.client-core
qpid-config -a $HOST:$PORT bind core.direct core.service-core core.service-core
qpid-config -a $HOST:$PORT bind core.direct core.trace core.trace
